version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    # environment:
      # NEXT_PUBLIC_API_URL: "http://localhost:8080"
    env_file:
      - .env
    command: /bin/sh -c "npm run dev"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      TEST: development
    env_file:
      - .env
    # command: /bin/sh -c "gunicorn"